name: Docker

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
  
jobs:
  update-docker-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build ilp-node
        if: startsWith(github.ref_name, 'v') == true
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: eqlabs/beaconchain-prometheus-exporter:${{github.ref_name}}
          build-args: |
            CARGO_BUILD_OPTION=--release
            RUST_BIN_DIR_NAME=release